[supervisord]
nodaemon=true
user=root
logfile=/var/log/waterscribe/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=5
numprocs=1
startsecs=0
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/log/waterscribe/nginx.err.log
stdout_logfile=/var/log/waterscribe/nginx.out.log

[program:gunicorn]
command=gunicorn --bind 127.0.0.1:8000 --workers 3 --timeout 60 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100 waterscribe_prod:app
directory=/app
user=app
autostart=true
autorestart=true
startretries=5
startsecs=5
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/log/waterscribe/gunicorn.err.log
stdout_logfile=/var/log/waterscribe/gunicorn.out.log

[eventlistener:supervisor_crashed]
command=/bin/bash -c "echo 'Supervisor crashed!' && exit 1"
events=PROCESS_STATE_FATAL