"""Initial migration with all models

Revision ID: a717e3b2a41f
Revises: 
Create Date: 2026-02-15 13:01:25.284425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a717e3b2a41f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('aquariums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('volume_gallons', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aquariums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aquariums_user_id'), ['user_id'], unique=False)

    op.create_table('fish_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fish_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fish_inventory_aquarium_id'), ['aquarium_id'], unique=False)

    op.create_table('maintenance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_log_aquarium_id'), ['aquarium_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('next_due', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('specific_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_aquarium_id'), ['aquarium_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_next_due'), ['next_due'], unique=False)

    op.create_table('water_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('ammonia', sa.Float(), nullable=True),
    sa.Column('nitrite', sa.Float(), nullable=True),
    sa.Column('nitrate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_parameters_aquarium_id'), ['aquarium_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_parameters_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_parameters_timestamp'))
        batch_op.drop_index(batch_op.f('ix_water_parameters_aquarium_id'))

    op.drop_table('water_parameters')
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_next_due'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_aquarium_id'))

    op.drop_table('scheduled_tasks')
    with op.batch_alter_table('maintenance_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_maintenance_log_aquarium_id'))

    op.drop_table('maintenance_log')
    with op.batch_alter_table('fish_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fish_inventory_aquarium_id'))

    op.drop_table('fish_inventory')
    with op.batch_alter_table('aquariums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aquariums_user_id'))

    op.drop_table('aquariums')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
